In [9]:
import numpy as np

# 1 - 99 사이의 랜덤 정수 값 2 * 8 크기 배열로 생성
A = np.random.randint(1, 99, size=(2, 8))

# A 벡터의 차원 정보 및 각 서브 벡터 크기 출력, 벡터의 저장된 모든 값 출력
print(A.shape)
print(A.shape[0])
print(A.shape[1])
# print(type(A))  # <class 'numpy.ndarray'>
print(A)
print('----------------------------')

# All Max 계산
maxZ = A[0][0]
for i in range(A.shape[0]):
  for j in range(A.shape[1]):
    if A[i][j] > maxZ:
      maxZ = A[i][j]

#SubMax 0 계산
maxX = A[0][0]
for i in range(A.shape[1]):
  if A[0][i] > maxX:
    maxX = A[0][i]

# SubMax 2 계산
maxY = A[1][0]
for i in range(A.shape[1]):
  if A[1][i] > maxY:
    maxY = A[1][i]

print('All Max: ', maxZ)
print('SubMax 0: ', maxX)
print('SubMax 1: ', maxY)
print('----------------------------')

# 2차원 벡터 A를 2*2*4 크기의 3차원 벡터 B로 변환
B = A.reshape(2, 2, 4)
print(B.shape)
print(B)
print('----------------------------')

# B벡터의 [][][0,1]에 저장된 값을 새로운 벡터 C에 [][][2,3]에 저장
C = B.copy()  # 벡터의 복사는 a=b 형식으로 불가능
C[:,:,2:] = B[:,:,:2] # C[:,:,2:4] = B[:,:, 0:2]
C[:,:,:2] = B[:,:,2:] # C[:,:,0:2] = B[:,:,2:4]
print(C)

(2, 8)
2
8
[[78 47 66 51 53 45 15 56]
 [96 47 70 69 71 45 47 83]]
----------------------------
All Max:  96
SubMax 0:  78
SubMax 1:  96
----------------------------
(2, 2, 4)
[[[78 47 66 51]
  [53 45 15 56]]

 [[96 47 70 69]
  [71 45 47 83]]]
----------------------------
[[[66 51 78 47]
  [15 56 53 45]]

 [[70 69 96 47]
  [47 83 71 45]]]
