In [9]:
# 실습 과제 1
import numpy as np

A = np.random.randint(1, 99, size=(2, 8))
print(type(A))
print(A.shape)
print(A.shape[0])
print(A.shape[1])
print(A)

submax_0 = A[0][0]
for i in range(A.shape[1]):
  if A[0][i] > submax_0:
    submax_0 = A[0][i]

submax_1 = A[1][0]
for i in range(A.shape[1]):
  if A[1][i] > submax_1:
    submax_1 = A[1][i]

print("All Max: ", max(submax_0, submax_1))
print("SubMax 0: ", submax_0)
print("SubMax 1: ", submax_1)

B = A.reshape(2, 2, 4)
print(B.shape)
print(B)

# 실습 과제2
print("실습 2")
C = B.copy()
print("copy본")
print(C)
tmp1 = B[:,:,0:2]
tmp2 = B[:,:,2:4]

C[:,:,2:4] = tmp1
C[:,:,:2] = tmp2

# C[:,:,2:] = B[:,:,:2]
# C[:,:,:2] = B[:,:,2:]

print(C)


<class 'numpy.ndarray'>
(2, 8)
2
8
[[56 50 39 41 41 83 52 61]
 [78  9 43 64 35 59 75 29]]
All Max:  83
SubMax 0:  83
SubMax 1:  78
(2, 2, 4)
[[[56 50 39 41]
  [41 83 52 61]]

 [[78  9 43 64]
  [35 59 75 29]]]
실습 2
copy본
[[[56 50 39 41]
  [41 83 52 61]]

 [[78  9 43 64]
  [35 59 75 29]]]
[[[39 41 56 50]
  [52 61 41 83]]

 [[43 64 78  9]
  [75 29 35 59]]]
